### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-vscode#1]
1. click into xml layout
2. F1 
3. Enter Haxeui: Open Preview

I get a blank window.  Is there some debug somewhere I can supply in order to help?

**Comment by ibilon** [comment]
There's currently no error support if the xml is invalid, or not self contained.
I'll add a print of the error.

**Comment by hoseyjoe** [comment]
The issue might have been i had a style  in xml
<style source="../css/main.css" />
removing that fixed the blank window.
